import type { MemoryCollection } from "./types";

export const MOCK_COLLECTIONS: MemoryCollection[] = [
  {
    id: "col_ai_interview",
    title: "AI Interview Preparation",
    description:
      "Complete guide covering Machine Learning, Neural Networks, Transformers, and LLMs for top-tier tech interviews.",
    author: "Harini",
    organization: "Tech Innovators",
    category: "Career",
    tags: ["AI", "Interview", "Machine Learning", "Career"],
    memoryCount: 145,
    lastUpdated: new Date(Date.now() - 86400000 * 2).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    downloads: 4200,
    views: 12500,
    forks: 850,
    rating: 4.9,
    license: "MIT",
    visibility: "public",
    version: "2.1.0",
    isTrending: true,
    isFeatured: true,
  },
  {
    id: "col_sys_design",
    title: "System Design Notes",
    description:
      "Architectural patterns, scalability, microservices, and databases for large-scale distributed systems.",
    author: "Alex_Dev",
    category: "Technology",
    tags: ["Architecture", "System Design", "Backend"],
    memoryCount: 89,
    lastUpdated: new Date(Date.now() - 86400000 * 5).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 120).toISOString(),
    downloads: 3100,
    views: 8900,
    forks: 412,
    rating: 4.8,
    license: "Apache 2.0",
    visibility: "public",
    version: "1.5.2",
    isTrending: true,
  },
  {
    id: "col_violin",
    title: "Violin Masterclass",
    description:
      "A comprehensive journey through Carnatic violin techniques, ragas, and compositions.",
    author: "Music Academy",
    organization: "Conservatory",
    category: "Music",
    tags: ["Music", "Violin", "Carnatic"],
    memoryCount: 56,
    lastUpdated: new Date(Date.now() - 86400000 * 10).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 60).toISOString(),
    downloads: 1200,
    views: 3400,
    forks: 150,
    rating: 4.9,
    license: "CC-BY-4.0",
    visibility: "public",
    version: "1.0.0",
    isFeatured: true,
  },
  {
    id: "col_react_guide",
    title: "React Complete Guide",
    description:
      "Modern React with Next.js App Router, Server Components, Server Actions, and Tailwind CSS.",
    author: "FrontendMasters",
    category: "Technology",
    tags: ["React", "Next.js", "Web Dev"],
    memoryCount: 210,
    lastUpdated: new Date(Date.now() - 86400000 * 1).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 200).toISOString(),
    downloads: 8500,
    views: 22000,
    forks: 1200,
    rating: 4.7,
    license: "MIT",
    visibility: "public",
    version: "4.0.0",
    isTrending: true,
  },
  {
    id: "col_healthcare",
    title: "Healthcare Research",
    description:
      "Aggregated papers and clinical trial summaries on modern diagnostic technologies.",
    author: "MedAI Labs",
    organization: "Medical Research",
    category: "Science",
    tags: ["Healthcare", "Research", "Medicine"],
    memoryCount: 340,
    lastUpdated: new Date(Date.now() - 86400000 * 15).toISOString(),
    createdAt: new Date(Date.now() - 86400000 * 365).toISOString(),
    downloads: 950,
    views: 4100,
    forks: 85,
    rating: 4.5,
    license: "Proprietary",
    visibility: "organization",
    version: "3.2.1",
  },
];

export const MOCK_CATEGORIES = [
  "Technology",
  "Science",
  "Music",
  "Career",
  "Education",
  "Healthcare",
  "Art",
  "Productivity",
];
